GET http://localhost:8080/api/courses
Accept: application/json

###
GET http://localhost:8080/api/courses/1
Accept: application/json

###
POST http://localhost:8080/api/courses
Content-Type: application/json

{
  "name": "asdf",
  "category": "back-end"
}

###
PUT http://localhost:8080/api/courses/1
Content-Type: application/json

{
  "id": 1,
  "name": "Angular com Spring v2",
  "category": "front-end"
}

###
DELETE http://localhost:8080/api/courses/1
Accept: application/json

###
